watch_dir: "/home/vboxuser/ymalfiles"
auxiliary_watch_dir: "/home/vboxuser/ymalfiles.enabled"
debounce_seconds: 1.5
status_check:
  process_name: "cron"
  min_uptime_seconds: 5
  retries: 5
  delay_seconds: 10

servers:
  - host: "192.168.56.102"
    ssh_port: 22
    api_port: 5000
    username: "vboxuser"
    key_filename: "/home/vboxuser/.ssh/id_ed25519"
    remote_path: "/home/vboxuser/ymalfiles"
    auxiliary_remote_path: "/home/vboxuser/ymalfiles.enabled"
